stages:
  - build
  - quality
  - test

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mariadb
  DB_CONNECTION: mysql

build:
  stage: build
  services:
    - mariadb:10.4 # the version you use in ddev config

  image: chilio/laravel-dusk-ci:php-8.1
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # - npm install # if you need to install additional modules from your projects package.json
    # - npm run dev # if you need to run dev scripts for example laravel mix
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      # these are only examples, you should modify them according to your project,
      # or remove cache routines entirely, if they are causing any problems on your next builds..
      # below are 2 safe ones if you use composer install and npm install in your stage script
      - vendor
      # - /resources/assets/vendors  # for example if you put your vendor node-libraries there

lint:
  stage: quality
  image: chilio/laravel-dusk-ci:php-8.1
  script:
    - wget https://github.com/symfony-cli/symfony-cli/releases/download/v5.8.7/symfony-cli_linux_amd64.tar.gz
    - tar -xvzf symfony-cli_linux_amd64.tar.gz symfony && rm -rf symfony-cli_linux_amd64.tar.gz
    - mv symfony vendor/bin
    - cp .env.example.ci .env
    - "./vendor/bin/symfony security:check"
#    - "./vendor/bin/ecs check"
    - "./vendor/bin/php-cs-fixer fix --dry-run --diff"
#    - "./vendor/bin/rector process --dry-run"
#    - "./vendor/bin/tlint lint"
#    - "./vendor/bin/phpstan analyse --memory-limit=2G"
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - vendor
    policy: pull

test: 
  stage: test
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - vendor
      - node_modules
    policy: pull

  services:
    - mariadb:10.4 # the version you use in ddev config

  image: chilio/laravel-dusk-ci:php-8.1
  script:
    - cp .env.example.ci .env
    - chmod -R 775 storage
    - chmod 775 bootstrap/cache
    - chown -R www-data ./
    - php artisan key:generate
    - php artisan migrate:fresh --seed

    - ./vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --stderr

  artifacts:
    paths:
      - ./build # Coverage Report
      - ./storage/logs # for debugging
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
